### ISSUE TITLE
VirtualHook on x86

### ISSUE THREAD

**Issue by rrrfff** [rk700/VirtualHook#13]
应用虽然没有x86的libs, 但借助houdini在x86平台正常打开, 并无异常。
然而相同应用使用VirtualHook却装载失败，看日志出现了以下异常, 是lib指令集问题, 不知道可有解决方案?

E/art     ( 3403): dlopen("/data/user/0/io.virtualhook/virtual/data/app/com.jingdong.pdj/lib/libjdpdj.so", RTLD_LAZY) failed: dlopen failed: "/data/user/0/io.virtualhook/virtual/data/app/com.jingdong.pdj/lib/libjdpdj.so" has unexpected e_machine: 40
D/AndroidRuntime( 3403): Shutting down VM
E/uncaught( 3403): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/io.virtualhook/virtual/data/app/com.jingdong.pdj/lib/libjdpdj.so" has unexpected e_machine: 40
E/uncaught( 3403):      at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/uncaught( 3403):      at java.lang.System.loadLibrary(System.java:989)
E/uncaught( 3403):      at jd.net.z.<clinit>(z.java:15)
E/uncaught( 3403):      at jd.net.ServiceProtocol.baseUrl(ServiceProtocol.java:1838)
E/uncaught( 3403):      at jd.net.ServiceProtocol.getUpdateResponse(ServiceProtocol.java:2183)
E/uncaught( 3403):      at jd.UpdateServer.checkUpdate(UpdateServer.java:65)
E/uncaught( 3403):      at pdj.start.StartActivity.onCreate(StartActivity.java:237)
E/uncaught( 3403):      at android.app.Activity.performCreate(Activity.java:5933)
E/uncaught( 3403):      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/uncaught( 3403):      at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:244)
E/uncaught( 3403):      at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:92)
E/uncaught( 3403):      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
E/uncaught( 3403):      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
E/uncaught( 3403):      at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/uncaught( 3403):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/uncaught( 3403):      at android.os.Handler.dispatchMessage(Handler.java:102)
E/uncaught( 3403):      at android.os.Looper.loop(Looper.java:135)
E/uncaught( 3403):      at android.app.ActivityThread.main(ActivityThread.java:5221)
E/uncaught( 3403):      at java.lang.reflect.Method.invoke(Native Method)
E/uncaught( 3403):      at java.lang.reflect.Method.invoke(Method.java:372)
E/uncaught( 3403):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/uncaught( 3403):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
I/art     ( 3403): System.exit called, status: 0
I/AndroidRuntime( 3403): VM exiting with result code 0, cleanup skipped.

**Comment by rrrfff** [comment]
问题解决,移出
