### ISSUE TITLE
 virtualHOOK运行一段时间就弹出无响应

### ISSUE THREAD

**Issue by ws15621066586** [rk700/VirtualHook#42]
要HOOK一个函数，只要调用origin 函数，运行一段时间就会弹出 virtualHOOK无响应的提示。HOOK别的函数却没有这问题，这是什么原因呢

**Comment by ws15621066586** [comment]
不是静态方法

**Comment by ws15621066586** [comment]
hook方法中什么也不写，只调用origin方法，运行一段时间也会出现virtualHOOK无响应的提示

**Comment by rk700** [comment]
信息太少，没法确定你的问题

**Comment by ws15621066586** [comment]
public static String className = "com.te.android.view.Refresh";
    public static String methodName = "bindData";
    public static String methodSig = "(Landroid/view/View;Lcom/te/android/v2/Order;Z)V";
    public static void hook(Object a, Object b, Object c,boolean d) {
        origin(a,b,c,d);
        return ;
    }
    public static void origin(Object a, Object b, Object c,boolean d) {
        Log.d("dddd","ddddd");
        return ;
    }

**Comment by ws15621066586** [comment]
YAHFA 别的地方都没动

**Comment by ws15621066586** [comment]
virtualhook 别的地方都没动,只有加上origin运行一段时间就会弹出 virtualHOOK无响应的提示！我也只能提供这么多信息了，别的也没什么信息了！！把要HOOK的发给你，测试下吗？

**Comment by ws15621066586** [comment]
virtualhook 别的地方都没动,只有加上origin运行一段时间就会弹出 virtualHOOK无响应的提示！我也只能提供这么多信息了，别的也没什么信息了！！把要HOOK的发给你，测试下吗？

**Comment by rk700** [comment]
设备是什么？系统是什么？日志是什么？hook的应用是什么？

**Comment by ws15621066586** [comment]
小米4X  ，安卓6.0的

**Comment by ws15621066586** [comment]
小米4X ，安卓6.0的，无响应找不到日志

**Comment by ws15621066586** [comment]
不是不发错误日志，错误日志实在太多了，跟设备没关系，下面是我摘出的可能有关的日志

**Comment by ws15621066586** [comment]
09-14 13:10:51.647 9539-9539/? E/ActivityThread: Service com.lody.virtual.client.stub.StubJob has leaked ServiceConnection com.lody.virtual.client.stub.StubJob$JobSession@2d396cc4 that was originally bound here
                                                 android.app.ServiceConnectionLeaked: Service com.lody.virtual.client.stub.StubJob has leaked ServiceConnection com.lody.virtual.client.stub.StubJob$JobSession@2d396cc4 that was originally bound here
                                                     at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1125)
                                                     at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1019)
                                                     at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1882)
                                                     at android.app.ContextImpl.bindService(ContextImpl.java:1865)
                                                     at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
                                                     at com.lody.virtual.client.stub.StubJob$1.startJob(StubJob.java:67)
                                                     at android.app.job.IJobService$Stub.onTransact(IJobService.java:61)
                                                     at android.os.Binder.execTransact(Binder.java:451)
09-14 13:10:51.800 14770-14797/? E/ActivityThread: Failed to find provider info for com.ss.android.article.news.umeng.message
09-14 13:10:51.804 14770-14800/? E/ActivityThread: Failed to find provider info for com.ss.android.article.news.umeng.message
09-14 13:10:51.805 14770-14800/? E/ActivityThread: Failed to find provider info for com.ss.android.article.news.umeng.message
09-14 13:10:51.846 14770-14797/? E/com.umeng.message.common.UmengMessageDeviceConfig: Could not read meta-data UMENG_MESSAGE_SECRET from AndroidManifest.xml.
09-14 13:10:51.878 14770-14797/? E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
09-14 13:10:51.980 788-950/? E/NativeCrashListener: Exception dealing with report
                                                    android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                        at libcore.io.Posix.readBytes(Native Method)
                                                        at libcore.io.Posix.read(Posix.java:147)
                                                        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                        at android.system.Os.read(Os.java:364)
                                                        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

**Comment by ws15621066586** [comment]
09-14 13:11:00.790 951-951/? E/HelperUtils: readFreezeAppInfoPkgname
                                            java.io.FileNotFoundException: /data/system/freezeappinfo.xml: open failed: ENOENT (No such file or directory)
                                                at libcore.io.IoBridge.open(IoBridge.java:496)
                                                at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                at android.util.AtomicFile.openRead(AtomicFile.java:199)
                                                at com.gionee.softmanager.softmanager.utils.HelperUtils.readFreezeAppInfoPkgname(HelperUtils.java:676)
                                                at com.gionee.softmanager.softmanager.utils.HelperUtils.addPackage(HelperUtils.java:848)
                                                at com.gionee.softmanager.softmanager.receiver.PackgeChangedReceiver.onReceive(PackgeChangedReceiver.java:54)
                                                at android.app.ActivityThread.handleReceiver(ActivityThread.java:2751)
                                                at android.app.ActivityThread.access$1700(ActivityThread.java:167)
                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
                                                at android.os.Handler.dispatchMessage(Handler.java:111)
                                                at android.os.Looper.loop(Looper.java:194)
                                                at android.app.ActivityThread.main(ActivityThread.java:5536)
                                                at java.lang.reflect.Method.invoke(Native Method)
                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
                                             Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                at libcore.io.Posix.open(Native Method)
                                                at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                at libcore.io.IoBridge.open(IoBridge.java:482)
                                                at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                at android.util.AtomicFile.openRead(AtomicFile.java:199) 
                                                at com.gionee.softmanager.softmanager.utils.HelperUtils.readFreezeAppInfoPkgname(HelperUtils.java:676) 
                                                at com.gionee.softmanager.softmanager.utils.HelperUtils.addPackage(HelperUtils.java:848) 
                                                at com.gionee.softmanager.softmanager.receiver.PackgeChangedReceiver.onReceive(PackgeChangedReceiver.java:54) 
                                                at android.app.ActivityThread.handleReceiver(ActivityThread.java:2751) 
                                                at android.app.ActivityThread.access$1700(ActivityThread.java:167) 
                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                at android.os.Looper.loop(Looper.java:194) 
                                                at android.app.ActivityThread.main(ActivityThread.java:5536) 
                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by ws15621066586** [comment]
无响应时会报这个错：
09-15 10:20:58.095 791-950/? E/NativeCrashListener: Exception dealing with report
                                                    android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                        at libcore.io.Posix.readBytes(Native Method)
                                                        at libcore.io.Posix.read(Posix.java:147)
                                                        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                        at android.system.Os.read(Os.java:364)
                                                        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

**Comment by JamesLiAndroid** [comment]
LeEco x727 android 8.1 64位系统 ，安装插件app就黑屏卡死，然后重启后显示插件app已经加载，但是无法运行！尝试编译64位库，报以下错误：

Android NDK: WARNING: APP_STL gnustl_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    

... 

20 errors generated.
make: *** [D:/Dev/Android/workspace/VirtualHook/VirtualApp/lib/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs/va++/Foundation/IOUniformer.o] Error 1

	at com.android.build.gradle.tasks.ExternalNativeBuildTaskUtils.executeBuildProcessAndLogError(ExternalNativeBuildTaskUtils.java:302)

**Comment by rk700** [comment]
错误信息能再详细些么？包括运行失败的日志和编译错误的信息

**Comment by pengzee** [comment]
> LeEco x727 android 8.1 64位系统 ，安装插件app就黑屏卡死，然后重启后显示插件app已经加载，但是无法运行！尝试编译64位库，报以下错误：
> 
> Android NDK: WARNING: APP_STL gnustl_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.
> 
> ...
> 
> 20 errors generated.
> make: *** [D:/Dev/Android/workspace/VirtualHook/VirtualApp/lib/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs/va++/Foundation/IOUniformer.o] Error 1
> 
> ```
> at com.android.build.gradle.tasks.ExternalNativeBuildTaskUtils.executeBuildProcessAndLogError(ExternalNativeBuildTaskUtils.java:302)
> ```

怎么解决的？
