### ISSUE TITLE
LocationManagerService ClassNotFoundException 这个如何解决呢？

### ISSUE THREAD

**Issue by zhangfy068** [rk700/VirtualHook#49]
11-07 11:24:44.366 W/System.err(22498): java.lang.ClassNotFoundException: com.android.server.LocationManagerService
11-07 11:24:44.366 W/System.err(22498): 	at java.lang.Class.classForName(Native Method)
11-07 11:24:44.366 W/System.err(22498): 	at java.lang.Class.forName(Class.java:309)
11-07 11:24:44.366 W/System.err(22498): 	at lab.galaxy.yahfa.HookMain.doHookItemDefault(HookMain.java:54)
11-07 11:24:44.366 W/System.err(22498): 	at lab.galaxy.yahfa.HookMain.doHookDefault(HookMain.java:32)
11-07 11:24:44.366 W/System.err(22498): 	at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:335)
11-07 11:24:44.366 W/System.err(22498): 	at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:196)
11-07 11:24:44.366 W/System.err(22498): 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:114)
11-07 11:24:44.366 W/System.err(22498): 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:71)
11-07 11:24:44.366 W/System.err(22498): 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-07 11:24:44.366 W/System.err(22498): 	at android.os.Looper.loop(Looper.java:135)
11-07 11:24:44.366 W/System.err(22498): 	at android.app.ActivityThread.main(ActivityThread.java:5671)
11-07 11:24:44.366 W/System.err(22498): 	at java.lang.reflect.Method.invoke(Native Method)
11-07 11:24:44.366 W/System.err(22498): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-07 11:24:44.366 W/System.err(22498): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)

**Comment by rk700** [comment]
详细信息是什么，设备？app？
