### ISSUE TITLE
点击菜单Virtual Location时会停止运行

### ISSUE THREAD

**Issue by Dragons-yu** [rk700/VirtualHook#71]
05-02 19:14:40.341 1855-1855/io.virtualhook E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: io.virtualhook, PID: 1855
                                                              android.content.ActivityNotFoundException: Unable to find explicit activity class {io.virtualhook/io.virtualapp.home.location.VirtualLocationSettings}; have you declared this activity in your AndroidManifest.xml?
                                                                  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                                  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
                                                                  at android.app.Activity.startActivityForResult(Activity.java:4225)
                                                                  at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                  at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                  at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                  at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                  at android.app.Activity.startActivity(Activity.java:4522)
                                                                  at android.app.Activity.startActivity(Activity.java:4490)
                                                                  at io.virtualapp.home.HomeActivity.lambda$initMenu$4$HomeActivity(HomeActivity.java:133)
                                                                  at io.virtualapp.home.HomeActivity$$Lambda$3.onMenuItemClick(Unknown Source)
                                                                  at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                  at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                  at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
                                                                  at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                  at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
                                                                  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3121)
                                                                  at android.widget.AbsListView$3.run(AbsListView.java:4036)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

手机：nexus6
系统：Android7.1.1

**Comment by rk700** [comment]
感觉是VirtualApp的功能，可以试下只用VirtualApp
