### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by huopochuan** [rk700/VirtualHook#97]
java.lang.UnsatisfiedLinkError: Shared library "/data/user/0/io.virtualfasthook/virtual/data/app/com.tencent.mm/lib/libwcdb.so" already opened by ClassLoader 0x10027b; can't open in ClassLoader 0xbe2698d4
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.tencent.wcdb.database.SQLiteGlobal.<clinit>(SourceFile:68)
        at com.tencent.wcdb.database.SQLiteCipherSpec.<init>(SourceFile:79)
        at com.tencent.mm.cf.f.<clinit>(SourceFile:60)
        at com.tencent.mm.cf.f.a(SourceFile:107)
        at com.tencent.mm.plugin.bbom.PluginBigBallOfMud.configure(SourceFile:261)
        at com.tencent.mm.kernel.b.f.invokeConfigure(SourceFile:95)
        at com.tencent.mm.kernel.a.c$2.call(SourceFile:1198)
        at com.tencent.mm.kernel.a.b.e$1.run(SourceFile:1189)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by huopochuan** [comment]
安装插件后wxapp启动失败
